server {
    listen 80;
    server_name hrflow.novatech.io;
    # TODO: SSL (Théo)
    location / {
        proxy_pass http://localhost:3000;
    }
    location /logs/ {
        alias /var/log/hrflow/;
        autoindex on;
    }
}
server {
    listen 80;
    server_name staging.hrflow.novatech.io;
    location / {
        proxy_pass http://localhost:3100;
    }
}
