global:
  resolve_timeout: 5m
  slack_api_url: '${SLACK_WEBHOOK_URL}'

templates:
  - '/etc/alertmanager/templates/*.tmpl'

route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'slack-warning'

  routes:
    # P1 — réveille l'astreinte immédiatement
    - matchers:
        - severity = "p1"
      receiver: 'slack-p1'
      group_wait: 0s
      repeat_interval: 15m
      continue: false

    # Critical — canal #alertes-critiques
    - matchers:
        - severity = "critical"
      receiver: 'slack-critical'
      group_wait: 10s
      repeat_interval: 1h
      continue: false

    # Warning — canal #alertes-warning
    - matchers:
        - severity = "warning"
      receiver: 'slack-warning'
      continue: false

receivers:
  - name: 'slack-p1'
    slack_configs:
      - channel: '#astreinte-p1'
        username: 'AlertManager NovaTech'
        icon_emoji: ':rotating_light:'
        title: '[P1] 🚨 INCIDENT CRITIQUE — {{ .GroupLabels.alertname }}'
        text: |
          *Service :* {{ range .Alerts }}{{ .Labels.job }}{{ end }}
          *Résumé :* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          *Détail :* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
          *Runbook :* https://github.com/uvsq22306626/novatech-shipit/blob/main/docs/runbook-incident-p1.md
        send_resolved: true

  - name: 'slack-critical'
    slack_configs:
      - channel: '#alertes-critiques'
        username: 'AlertManager NovaTech'
        icon_emoji: ':warning:'
        title: '[CRITICAL] {{ .GroupLabels.alertname }}'
        text: |
          *Service :* {{ range .Alerts }}{{ .Labels.job }}{{ end }}
          *Résumé :* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
          *Détail :* {{ range .Alerts }}{{ .Annotations.description }}{{ end }}
        send_resolved: true

  - name: 'slack-warning'
    slack_configs:
      - channel: '#alertes-warning'
        username: 'AlertManager NovaTech'
        icon_emoji: ':bell:'
        title: '[WARNING] {{ .GroupLabels.alertname }}'
        text: |
          *Service :* {{ range .Alerts }}{{ .Labels.job }}{{ end }}
          *Résumé :* {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}
        send_resolved: true

inhibit_rules:
  - source_matchers:
      - severity = "p1"
    target_matchers:
      - severity =~ "warning|critical"
    equal: ['job']
