name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, api-gateway, paie, conges, recrutement]
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        working-directory: services/${{ matrix.service }}
        run: npm install

      - name: Vérifier la syntaxe
        working-directory: services/${{ matrix.service }}
        run: node --check src/index.js

      - name: Lancer les tests
        working-directory: services/${{ matrix.service }}
        run: npm run test --if-present

  security:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Audit des dépendances (auth)
        working-directory: services/auth
        run: npm audit --audit-level=high || true

      - name: Construire l'image Docker (auth)
        run: docker build -t auth-service:scan services/auth

      - name: Scan de l'image avec Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: auth-service:scan
          format: table
          exit-code: '0'
          severity: HIGH,CRITICAL
          # 🔒 Audit + Scan pour recrutement   
      - name: Audit des dépendances (recrutement)
        working-directory: services/recrutement
        run: npm audit --audit-level=high || true

      - name: Construire l'image Docker (recrutement)
        run: docker build -t recrutement-service:scan services/recrutement

      - name: Scan de l'image avec Trivy (recrutement)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: recrutement-service:scan
          format: table
          exit-code: '0'
          severity: HIGH,CRITICAL

  recrutement-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Installer les dépendances
        working-directory: services/recrutement
        run: npm install

      - name: Installer Playwright
        working-directory: services/recrutement
        run: npx playwright install --with-deps

      - name: Démarrer le service
        working-directory: services/recrutement
        run: |
          MOCK_DB=true npm start > server.log 2>&1 &

      - name: Attendre le démarrage du service
        working-directory: services/recrutement
        run: npx wait-on http://localhost:3004

      - name: Tests E2E
        working-directory: services/recrutement
        run: npm run test:e2e